import { StyleSheet } from "react-native";

import { COLORS } from "../../theme/colors";

export const authStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.canvas },
  scroll: { flexGrow: 1, justifyContent: "center", padding: 28 },
  brand: { alignItems: "center", marginBottom: 36 },
  brandMark: {
    width: 60,
    height: 60,
    borderRadius: 18,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
    shadowColor: COLORS.primaryDeep,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  brandMarkText: { color: COLORS.onPrimary, fontSize: 28, fontWeight: "900" },
  brandName: { color: COLORS.ink, fontSize: 22, fontWeight: "800", letterSpacing: -0.5 },
  brandTagline: { color: COLORS.inkMuted, fontSize: 13, marginTop: 4 },
  card: {
    backgroundColor: COLORS.surface,
    borderRadius: 22,
    padding: 26,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: 24,
    shadowColor: COLORS.ink,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 2,
  },
  heading: {
    color: COLORS.ink,
    fontSize: 22,
    fontWeight: "800",
    marginBottom: 4,
    letterSpacing: -0.4,
  },
  subheading: { color: COLORS.inkMuted, fontSize: 14, marginBottom: 26 },
  fieldGroup: { marginBottom: 18 },
  label: {
    color: COLORS.inkMuted,
    fontSize: 11,
    fontWeight: "700",
    marginBottom: 7,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  input: {
    borderWidth: 1.5,
    borderColor: COLORS.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    color: COLORS.ink,
    fontSize: 15,
    backgroundColor: COLORS.surfaceMuted,
  },
  error: {
    color: COLORS.error,
    fontSize: 13,
    marginBottom: 14,
    padding: 12,
    backgroundColor: "rgba(184,59,50,0.06)",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(184,59,50,0.15)",
  },
  button: {
    backgroundColor: COLORS.primary,
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: "center",
    marginTop: 6,
  },
  buttonDisabled: { opacity: 0.55 },
  buttonText: { color: COLORS.onPrimary, fontSize: 15, fontWeight: "800", letterSpacing: 0.1 },
  footer: { flexDirection: "row", justifyContent: "center", alignItems: "center" },
  footerText: { color: COLORS.inkMuted, fontSize: 14 },
  footerLink: { color: COLORS.primary, fontSize: 14, fontWeight: "700" },
});
