from __future__ import annotations

from datetime import datetime
from typing import Protocol

from apps.api.src.models.message import MessageReadReceipt, MessageThread, MessageThreadParticipant


class MessageThreadRepository(Protocol):
    def get(self, thread_id: str) -> MessageThread | None: ...

    def save(self, thread: MessageThread) -> MessageThread: ...

    def get_direct(self, shift_id: str, worker_id: str) -> MessageThread | None: ...

    def get_shift_group(self, shift_id: str) -> MessageThread | None: ...

    def get_employment(self, relationship_id: str) -> MessageThread | None: ...

    def list_for_venue(self, venue_id: str) -> list[MessageThread]: ...

    def list_employment_for_worker(self, worker_id: str) -> list[MessageThread]: ...

    def save_participant(self, participant: MessageThreadParticipant) -> MessageThreadParticipant: ...

    def close_participant(self, participant_id: str, left_at: datetime) -> MessageThreadParticipant: ...

    def list_participants(self, thread_id: str) -> list[MessageThreadParticipant]: ...

    def get_receipt(
        self, message_id: str, party_kind: str, party_id: str
    ) -> MessageReadReceipt | None: ...

    def save_receipt(self, receipt: MessageReadReceipt) -> MessageReadReceipt: ...
